### ISSUE TITLE
Idee: SSL-Zertifikate bei Installation von Software bereitstellen + DNS Prüfung

### ISSUE THREAD

**Issue by pavl21** [gnmyt/PowerTools#82]
Ich würde es hilfreich finden, wenn die SSL-Zertifikate für zum Beispiel Nextcloud direkt zur Verfügung gestellt werden. Vor der Installation soll zudem auch geprüft werden, ob ein DNS-Eintrag für den gewählten Server existiert, damit es da nicht fehlschlägt.

**Comment by gnmyt** [comment]
Jo, bau ich ein. Gerade der DNS-Teil is praktisch, gefällt mir. :)
