### ISSUE TITLE
Feature: CPU und RAM Stresstest

### ISSUE THREAD

**Issue by pavl21** [gnmyt/PowerTools#89]
Einige Hoster sagen, dass man entsprechend viel RAM und CPU bekommt. Leider entspricht es aber nicht immer die Wahrheit. Manchmal ist es auch so, das ein RAM kaputt ist. Mit einem Stresstest kann man das vorbeugen und allgemein auch testen, ob alles wie gewünscht zur Verfügung steht.

**Comment by gnmyt** [comment]
Das würde dann aber auch eine eigene Tool-Seite bekommen. Ich schau mal wie weit das umsetzbar ist, finde ich prinzipiell aber gut.
